---
- hosts: webservers
  become: true
  tasks:
    - name: copy war file to tomcat server
      copy:
        src: /opt/playbooks/webapp/target/webapp.war
        dest: /opt/apache-tomcat-9.0.71/webapps/
